export const collectorStories = [
  {
    id: 1,
    userId: 1,
    userName: "Ana García",
    userAvatar: "/placeholder.svg?height=40&width=40&text=AG",
    content: "¡Acabo de completar mi colección de la Liga Española 2023!",
    image: "/placeholder.svg?height=200&width=300&text=Colección+Completa",
    likes: 24,
    comments: 5,
    liked: false,
  },
  {
    id: 2,
    userId: 2,
    userName: "Carlos Rodríguez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=CR",
    content: "Busco el cromo número 7 de la colección Pokémon 25th Anniversary. ¿Alguien lo tiene?",
    likes: 12,
    comments: 8,
    liked: false,
  },
  {
    id: 3,
    userId: 3,
    userName: "Laura Martínez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=LM",
    content: "Acabo de conseguir un cromo super raro de la colección Marvel Cinematic Universe",
    image: "/placeholder.svg?height=200&width=300&text=Cromo+Raro",
    likes: 45,
    comments: 15,
    liked: false,
  },
  {
    id: 4,
    userId: 4,
    userName: "David Sánchez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=DS",
    content: "Organizando un evento de intercambio este fin de semana. ¿Quién se apunta?",
    likes: 30,
    comments: 22,
    liked: false,
  },
  {
    id: 5,
    userId: 5,
    userName: "Elena Gómez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=EG",
    content: "¡Nueva colección de Anime Legends ya disponible! ¿Alguien ya la empezó?",
    image: "/placeholder.svg?height=200&width=300&text=Anime+Legends",
    likes: 18,
    comments: 7,
    liked: false,
  },
]

