import { Collection } from "@/app/types";

export const collections: Collection[] = [
  {
    id: "1",
    name: "Pokémon 2023",
    image: "https://images.unsplash.com/photo-1621296443295-fc2b363d5ee5",
    year: 2023,
    publisher: "Nintendo",
    totalCards: 150,
    activeUsers: 1000,
    category: "videogames",
    popularity: 95,
    recentActivity: [
      "Ash completed a trade",
      "Rare Pikachu card found",
      "New booster pack released",
    ],
    lastUpdated: 2,
    likes: 1234,
    featured: true,
  },
  {
    id: "2",
    name: "FIFA World Cup 2022",
    image: "https://images.unsplash.com/photo-1601758003122-c1f6e3e1d91d",
    year: 2022,
    publisher: "Panini",
    totalCards: 300,
    activeUsers: 1500,
    category: "sports",
    popularity: 90,
    recentActivity: [
      "Cristiano Ronaldo card added",
      "Trade completed for Messi",
      "New stadium cards released",
    ],
    lastUpdated: 5,
    likes: 987,
    featured: false,
  },
  {
    id: "3",
    name: "Marvel Cinematic Universe",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90",
    year: 2023,
    publisher: "Topps",
    totalCards: 200,
    activeUsers: 1200,
    category: "movies",
    popularity: 88,
    recentActivity: [
      "Avengers Endgame card signed",
      "Iron Man rare card auctioned",
      "New Spider-Man collection released",
    ],
    lastUpdated: 1,
    likes: 756,
    featured: true,
  },
  {
    id: "4",
    name: "Anime Legends",
    image: "https://images.unsplash.com/photo-1562014760-196f9998e2a5",
    year: 2023,
    publisher: "Upper Deck",
    totalCards: 180,
    activeUsers: 800,
    category: "anime",
    popularity: 85,
    recentActivity: [
      "Naruto rare card found",
      "Limited edition Goku card released",
      "Community event planned",
    ],
    lastUpdated: 3,
    likes: 543,
    featured: false,
  },
  {
    id: "5",
    name: "Vintage Sports Cards",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c",
    year: 1995,
    publisher: "Topps",
    totalCards: 100,
    activeUsers: 600,
    category: "sports",
    popularity: 82,
    recentActivity: [
      "Michael Jordan rookie card sold",
      "Rare baseball card trade",
      "Historic auction planned",
    ],
    lastUpdated: 6,
    likes: 432,
    featured: true,
  },
]
