export const exchangeWall = [
  {
    id: 1,
    userId: 1,
    userName: "Ana García",
    userAvatar: "/placeholder.svg?height=40&width=40&text=AG",
    type: "offer",
    cardName: "Lionel Messi",
    collection: "Liga Española 2023",
    country: "España",
  },
  {
    id: 2,
    userId: 2,
    userName: "Carlos Rodríguez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=CR",
    type: "request",
    cardName: "Pikachu Holo",
    collection: "Pokémon 25th Anniversary",
    country: "México",
  },
  {
    id: 3,
    userId: 3,
    userName: "Laura Martínez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=LM",
    type: "offer",
    cardName: "Iron Man",
    collection: "Marvel Cinematic Universe",
    country: "Argentina",
  },
  {
    id: 4,
    userId: 4,
    userName: "David Sánchez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=DS",
    type: "request",
    cardName: "Naruto Uzumaki",
    collection: "Anime Legends",
    country: "Colombia",
  },
  {
    id: 5,
    userId: 5,
    userName: "Elena Gómez",
    userAvatar: "/placeholder.svg?height=40&width=40&text=EG",
    type: "offer",
    cardName: "Cristiano Ronaldo",
    collection: "UEFA Champions League 2023",
    country: "Portugal",
  },
]

